services:
    database:
        image: mysql:latest
        environment:
            MYSQL_DATABASE: 'ProjetBDD'
            MYSQL_USER: 'Zakuross'
            MYSQL_PASSWORD: 'pwd123'
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
            - 'greenhubdb:/var/lib/mysql'
        ports:
            - '3307:3306'

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: backend
        ports:
            - "8100:8100"
        environment:
            DB_CONNECTION: "mysql"
            DB_HOST: "database"
            DB_PORT: "3306"
            DB_DATABASE: "ProjetBDD"
            DB_USERNAME: "Zakuross"
            DB_PASSWORD: "pwd123"
volumes:
    greenhubdb:
